version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-add-repository --yes ppa:libccd-debs/ppa
            apt-add-repository --yes ppa:fcl-debs/ppa
            apt-add-repository --yes ppa:dartsim/ppa
            apt-get -qq update
            apt-get -qq --yes --force-yes install cmake libassimp-dev libboost-all-dev libccd-dev libeigen3-dev libfcl-dev freeglut3-dev  libxi-dev  libxmu-dev libbullet-dev libflann-dev libnlopt-dev coinor-libipopt-dev libtinyxml-dev libtinyxml2-dev liburdfdom-dev liburdfdom-headers-dev libopenscenegraph-dev
      - run:
          name: Build
          command: |
            mkdir build && cd build
            cmake ..
            make -j4 all
      - run:
          name: Test
          command: make test
