version: 2.0
jobs:
  build:
    docker:
      - image: gcc:6
    dependencies:
      pre:
        - sudo apt-add-repository --yes ppa:libccd-debs/ppa
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: cmake ..
      - run: make -j4
